{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexu.secretName" . }}
  namespace: {{ include "nexu.namespace" . }}
  labels:
    {{- include "nexu.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := omit .Values.secret "create" "existingSecretName" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
